# Generated by Django 5.2 on 2026-01-10 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-learners_count"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="courselist",
            options={
                "verbose_name": "Подкатегория",
                "verbose_name_plural": "Подкатегории",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-create_date"],
                "verbose_name": "Отзыв",
                "verbose_name_plural": "Отзывы",
            },
        ),
        migrations.AlterModelOptions(
            name="stepikuser",
            options={
                "verbose_name": "Пользователь на Stepik",
                "verbose_name_plural": "Пользователи на Stepik",
            },
        ),
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="begin_date",
        ),
        migrations.RemoveField(
            model_name="course",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="course",
            name="end_date",
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="external_id",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ID на Stepik"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Категория"),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="course",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_courses",
                to="parser.stepikuser",
                verbose_name="Авторы",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_lists",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="parser.courselist",
                verbose_name="Подкатегории",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="cover",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Обложка"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="course",
            name="external_id",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ID на Stepik"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="instructed_courses",
                to="parser.stepikuser",
                verbose_name="Преподаватели",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активный"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(
                default=False, verbose_name="Запись ещё не началась"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Платный"),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_public",
            field=models.BooleanField(
                default=True, verbose_name="Опубликован"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Язык"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="learners_count",
            field=models.IntegerField(
                default=0, verbose_name="Количество записавшихся"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Данные с запроса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="reviews_count",
            field=models.IntegerField(
                default=0, verbose_name="Количество оценок"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=500, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary",
            field=models.TextField(blank=True, verbose_name="О курсе"),
        ),
        migrations.AlterField(
            model_name="course",
            name="time_to_complete",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Время на выполнение (ак.ч.)",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Курс"),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="external_id",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ID на Stepik"
            ),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="title",
            field=models.CharField(
                max_length=500, verbose_name="Подкатегория"
            ),
        ),
        migrations.AlterField(
            model_name="courselist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="review",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="parser.course",
                verbose_name="Отзыв",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="create_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="external_id",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ID на Stepik"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="raw_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Данные с запроса"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.IntegerField(verbose_name="Оценка"),
        ),
        migrations.AlterField(
            model_name="review",
            name="text",
            field=models.TextField(
                blank=True, verbose_name="Комментарий к отзыву"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="update_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата изменения"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="parser.stepikuser",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="avatar",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Фото профиля"
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="bio",
            field=models.TextField(
                blank=True, verbose_name="Описание профиля"
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Создано"
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="details",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="Дополнительная информация",
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="external_id",
            field=models.IntegerField(
                db_index=True, unique=True, verbose_name="ID на Stepik"
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="ФИО"
            ),
        ),
        migrations.AlterField(
            model_name="stepikuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
    ]
