# Generated by Django 5.2 on 2026-01-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parser",
            "0002_alter_category_options_alter_course_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="rating",
        ),
    ]
