# Generated by Django 5.2 on 2026-01-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser", "0003_remove_course_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="platform",
            field=models.CharField(
                choices=[("stepik", "Stepik"), ("openedu", "OpenEdu")],
                default="stepik",
                max_length=50,
                verbose_name="Платформа",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("ru", "Русский"), ("en", "Английский")],
                max_length=10,
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="time_to_complete",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Время на выполнение (секунд)",
            ),
        ),
    ]
